CREATE DATABASE IF NOT EXISTS TMDB;

USE TMDB;

DROP TABLE IF EXISTS tmdb_info;

CREATE TABLE tmdb_info (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    title VARCHAR(64) DEFAULT NULL, 
    release_date VARCHAR(64) DEFAULT NULL,
    budget DOUBLE DEFAULT 0,
    revenue DOUBLE DEFAULT 0,
    runtime INT DEFAULT 0
) AUTO_INCREMENT=1;